Add IsType/IsNotType with typeof() parameter to generic overload
xunit/xunit.analyzers pull request #44
Opened 2017-05-08 09:11 UTC by ErikSchierboom

Note: I've use 2007 as the analyzer ID to account for the currently open PR #43 that already uses 2006.

Refs https://github.com/xunit/xunit/issues/1255

2017-05-08 13:56 UTC, marcind requested changes

2017-05-08 13:56 UTC, marcind commented on src/xunit.analyzers/Constants.cs
> +                "Do not use typeof value to check the type",
'typeof expression'

2017-05-08 13:56 UTC, marcind commented on src/xunit.analyzers/AssertIsTypeShouldUseGenericTypeFixer.cs
> +                    equivalenceKey: title),
Consider a less specific equivalence key so that 'Fix all occurrences' would work on all instances of the issue, e.g. "Use Assert.IsType<T>"

2017-05-08 13:56 UTC, marcind commented on src/xunit.analyzers/Constants.cs
> +                "The typeof('{0}') parameter should be removed and the '{0}' type added as a generic type to method '{1}'.",
Maybe something like "Do not use typeof({0}) expression to check the type"

2017-05-08 13:56 UTC, marcind commented on src/xunit.analyzers/Constants.cs
> +            internal static DiagnosticDescriptor X2007_AssertIsTypeShouldUseGenericType { get; } = new DiagnosticDescriptor("xUnit2007",
AssertIsTypeShouldUseGenericOverload

2017-05-08 14:15 UTC, ErikSchierboom commented
@marcind I've updated the PR with the requested changes. Thanks for reviewing this!

2017-05-08 16:35 UTC, marcind approved these changes
Looks great. Waiting for transition to .NET Foundation to merge.

2017-05-08 16:58 UTC, ErikSchierboom commented
👍

2017-05-09 00:42 UTC, marcind commented on src/xunit.analyzers/AssertIsTypeShouldUseGenericOverloadType.cs
> +        internal static HashSet<string> IsTypeMethods = new HashSet<string>(new[] { "IsType" });
Just realized we probably want to include `IsAssignableFrom` here as well

2017-05-09 05:51 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertIsTypeShouldUseGenericOverloadType.cs
> +        internal static HashSet<string> IsTypeMethods = new HashSet<string>(new[] { "IsType" });
Good catch. I'll update the PR.

2017-05-09 18:00 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertIsTypeShouldUseGenericOverloadType.cs
> +        internal static HashSet<string> IsTypeMethods = new HashSet<string>(new[] { "IsType" });
@marcind I've added `IsAssignableFrom` to the PR.

2017-05-19 23:09 UTC, marcind commented
Closing/reopening for CLA bot

2017-05-19 23:10 UTC, dnfclas commented
@ErikSchierboom,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-05-20 00:00 UTC, closed without merging