Add bool regex match to regex match comparison
xunit/xunit.analyzers pull request #45
Opened 2017-05-08 13:45 UTC by ErikSchierboom

Refs https://github.com/xunit/xunit/issues/1261

2017-05-08 21:09 UTC, marcind requested changes

2017-05-08 21:09 UTC, marcind commented on test/xunit.analyzers.tests/CodeAnalyzerHelper.cs
> +        static readonly MetadataReference SystemTextReference = MetadataReference.CreateFromFile(typeof(System.Text.RegularExpressions.Regex).GetTypeInfo().Assembly.Location);
Is this necessary? The unit tests run on the Desktop framework so this would resolve to System.dll, which should already be included.

2017-05-08 21:09 UTC, marcind commented on src/xunit.analyzers/AssertRegexMatchShouldNotUseBoolLiteralCheckFixer.cs
> +                editor.ReplaceNode(invocation,
How robust is this refactoring? E.g. for code like in the unit test FindsWarning_ForInstaceRegexIsMatchWithConstructedRegexVariable, will it do the right thing? What if the regex reference is a parameter, or a field on some other class?

2017-05-08 21:09 UTC, marcind commented on src/xunit.analyzers/AssertRegexMatchShouldNotUseBoolLiteralCheckFixer.cs
> +                editor.ReplaceNode(invocation,
This makes me wonder if it's worth having this analyzer for the instance method at all. Maybe just the static method?

2017-05-09 05:49 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertRegexMatchShouldNotUseBoolLiteralCheckFixer.cs
> +                editor.ReplaceNode(invocation,
@marcind Actually, it should also work for those scenarios. I've tested it with two variants:

1. The `Regex` object is _new-ed_ inline
1. The `Regex` object is a variable

I did not test with a parameter, but that should also work. I'll test it tonight. As for the robustness, I think it is good here, as what I am doing is just taking the left part of `x.IsMatch` and using that as the first parameter. Perhaps you could try it on your machine?

2017-05-09 05:49 UTC, ErikSchierboom commented on test/xunit.analyzers.tests/CodeAnalyzerHelper.cs
> +        static readonly MetadataReference SystemTextReference = MetadataReference.CreateFromFile(typeof(System.Text.RegularExpressions.Regex).GetTypeInfo().Assembly.Location);
It was on my machine, but I'll verify.

2017-05-09 16:13 UTC, marcind commented on src/xunit.analyzers/AssertRegexMatchShouldNotUseBoolLiteralCheckFixer.cs
> +                editor.ReplaceNode(invocation,
Yeah, thinking about this again, instance methods are good. I wasn't thinking straight yesterday.

2017-05-09 16:15 UTC, marcind commented on test/xunit.analyzers.tests/CodeAnalyzerHelper.cs
> +        static readonly MetadataReference SystemTextReference = MetadataReference.CreateFromFile(typeof(System.Text.RegularExpressions.Regex).GetTypeInfo().Assembly.Location);
I think this is actually a reference to System.dll (at least on desktop), which doesn't look like it was explicitly referenced here yet.

2017-05-09 16:15 UTC, marcind approved these changes
Waiting for .NET Foundation transition to complete.

2017-05-19 23:10 UTC, marcind commented
Closing/reopening for CLA bot

2017-05-19 23:10 UTC, dnfclas commented
@ErikSchierboom,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-05-20 00:07 UTC, closed without merging