Add analyzer to replace Assert.Collection with Assert.Empty when no Action is specified
xunit/xunit.analyzers pull request #55
Opened 2017-06-05 17:18 UTC by ErikSchierboom

Refs https://github.com/xunit/xunit/issues/1256

2017-06-05 17:18 UTC, dnfclas commented
@ErikSchierboom,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-11 06:57 UTC, marcind requested changes

2017-06-11 06:57 UTC, marcind commented on src/xunit.analyzers/Descriptors.cs
> +        internal static DiagnosticDescriptor X2011_AssertCollectionEmptyCheckShouldNotUseCollectionCheckFixer { get; } = new DiagnosticDescriptor("xUnit2011",
Accidental "Fixer" suffix?

2017-06-11 06:57 UTC, marcind commented on src/xunit.analyzers/AssertCollectionEmptyCheckShouldNotUseCollectionCheckFixer.cs
> +            context.RegisterCodeFix(
I think there should be an alternative fixer for this, which would add an element inspector. If you don't have the bandwidth/interest to implement that we could open a follow up issue instead.

2017-06-11 11:31 UTC, ErikSchierboom commented on src/xunit.analyzers/Descriptors.cs
> +        internal static DiagnosticDescriptor X2011_AssertCollectionEmptyCheckShouldNotUseCollectionCheckFixer { get; } = new DiagnosticDescriptor("xUnit2011",
Whoops. I'll fix it

2017-06-11 11:32 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertCollectionEmptyCheckShouldNotUseCollectionCheckFixer.cs
> +            context.RegisterCodeFix(
Excellent suggestion. I'll add it to the PR

2017-06-12 09:06 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertCollectionEmptyCheckShouldNotUseCollectionCheckFixer.cs
> +            context.RegisterCodeFix(
@marcind I've added a second code fix to add an element inspector. At the moment, the inspector is just an empty lamdba: `x => { }`. Is that okay or would you like to use something else?

I've also slightly renamed the code fix to not have it tied to the empty collection check.

2017-06-13 16:58 UTC, marcind approved these changes

2017-06-13 16:58 UTC, merged