Add Assert.Throws/ThrowsAny analyzer
xunit/xunit.analyzers pull request #63
Opened 2017-07-24 15:05 UTC by ErikSchierboom

Refs https://github.com/xunit/xunit/issues/1248

2017-07-24 15:06 UTC, dnfclas commented
@ErikSchierboom,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-07-24 19:13 UTC, marcind commented
The generic versions of Assert.Throws have overrides that match a Task-returning method that are marked as obsolete with error, so the following two usages are already marked as compilation errors:

```C#
Assert.Throws<Exception>(() => Foo());
Assert.Throws<ArgumentException>("foo", () => Foo());
```

In those cases the analyzer should not raise an additional warning but just provide a refactoring to fix the problem.

The 3rd handled case `Assert.Throws(typeof(Exception), () => Foo());` does not have an obsoleted overload for some reason, but causes a runtime error thus in this case the analyzer should produce an error.

2017-07-24 19:58 UTC, ErikSchierboom commented
Ah good point. How can I best do that?

2017-07-24 20:06 UTC, marcind requested changes

2017-07-24 20:06 UTC, marcind commented on src/xunit.analyzers/AssertThrowsShouldNotBeUsedForAsyncThrowsCheckFixer.cs
> +            return
This implementation builds a return type expression that's fully namespace qualified, even if the document already has the `System.Threading.Tasks` namespace included. I've used `editor.Generator.TypeExpression` to get something takes the imported namespaces into account.

2017-07-24 20:12 UTC, marcind commented
There's `Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider`, but I have not explored it that much. It could also probably be done using one descriptor with a severity of hidden (see X2001_AssertEqualsShouldNotBeUsed) and one with an Error.

2017-07-25 06:26 UTC, ErikSchierboom commented on src/xunit.analyzers/AssertThrowsShouldNotBeUsedForAsyncThrowsCheckFixer.cs
> +            return
Thanks for the tip! I didn't know how to do that, so that's why I used the fully qualified namespace.

2017-07-25 18:04 UTC, ErikSchierboom commented
@marcind I've updated the PR with the following changes:

- The two obsolete methods are not flagged as warnings anymore but use the hidden severity.
- I've added unit tests for the paramName overload (forgot about them).
- I've used `editor.Generator.TypeExpression` to generate the minimal `Task` return type syntax.
- I've rebased on the latest `master`.

2017-07-25 18:21 UTC, marcind requested changes

2017-07-25 18:21 UTC, marcind commented on src/xunit.analyzers/Descriptors.cs
> +            Categories.Assertions, DiagnosticSeverity.Warning, isEnabledByDefault: true);
This should be Error, since not addressing the problem will cause the test to fail at runtime.

2017-07-25 18:51 UTC, ErikSchierboom commented on src/xunit.analyzers/Descriptors.cs
> +            Categories.Assertions, DiagnosticSeverity.Warning, isEnabledByDefault: true);
Fixed!

2017-07-25 18:56 UTC, merged

2017-07-25 18:58 UTC, ErikSchierboom commented
Thanks for the thorough reviews!