Refactoring: Split Extensions into two and move it to Utilities
xunit/xunit.analyzers pull request #72
Opened 2017-08-12 22:24 UTC by jamesqo

The methods in the `Extensions` class seem really random. Apart from them being related to types from Roslyn, they don't really have a coherent theme-- some methods are related to syntax, others to symbols. I split `Extensions` into two new classes, `SyntaxExtensions` and `SymbolExtensions`, and put them in the `Utilities` subdirectory.

/cc @marcind, @ErikSchierboom

2017-08-12 22:24 UTC, dnfclas commented
@jamesqo,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-12 23:46 UTC, marcind requested changes
I typically start a project simple until the right organizational patterns emerge. Looks like its time for those extension methods. However, I would prefer the namespace not to change so that it's easier for intellisense to kick in. Otherwise looks good.

2017-08-13 04:03 UTC, jamesqo commented
> However, I would prefer the namespace not to change so that it's easier for intellisense to kick in. Otherwise looks good.

I disagree a bit there, it's a bit weird if some 'utility' classes are in `Utililties/` and some are not, but sure, I've changed the namespace. Feel free to merge.

2017-08-13 08:37 UTC, ErikSchierboom approved these changes

2017-08-13 13:34 UTC, marcind approved these changes

2017-08-13 13:34 UTC, merged