Add negative zero as unique value for xUnit1025.
xunit/xunit.analyzers pull request #99
Opened 2018-02-16 22:02 UTC by wachulski

Note! This does not cover all possible cases. A trade-off has been made between
algorithm complexity and its ability to catch most common scenarios.
Nested values like (1, new object[] {-0.0}) are disregarded (in this case
it duplicates (1, new object[] {0.0}).

InlineDataShouldBeUniqueWithinTheory analyzer has been refactored.
A common model for argument values created. That led to reduction
of syntax pattern matching - the algorithm got simplified. The common model
has been extracted out to Utilities.

Test method names were decoupled from the severity of returned diagnostics.

2018-02-23 17:35 UTC, marcind requested changes
Could you undo the test method rename changes (or at least separate into a different PR)? I prefer to keep functional changes separate from stylistic/cleanup/etc.

2018-02-24 22:17 UTC, wachulski commented
Done, as you wished.

2018-02-26 19:08 UTC, marcind requested changes
I'm a bit torn on this set of changes.

It looks like it achieves the goal of handling simple usages of negative/positive floating 0. As you state, it does not handle more complex (albeit unlikely to be used cases). I'd like to see a unit test for the unhandled case as a form of documentation that this is intentional (I also wonder if the old implementation of the comparison algorithm would handle that case).

As to the rewrite, seems like the goals was to a) simplify the code/reduce duplication and b) optimize performance by reducing boxing and allocations. I'm a little worried here because it looks like there's at least 1 place that introduces a bug (the unchanging `index` variable) and I'm not convinced the perf gains are there. From the perf side, the critical path is the calculation of the hash code for each inline row. I'm not saying the previous version of the code was great at it, but neither is the new one (given the potential for multiple ImmutableArrays being created).

My suggestion would be to try what the -0.0 handling would look like in the existing algorithm, add the tests, and then potentially take a stab at an improved algorithm that takes the performance of the whole analyzer into consideration.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        private static AttributeSyntax GetAttributeSyntax(SymbolAnalysisContext context, AttributeData attribute)
Moving this method was unnecessary.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +            return true;
Isn't this unreachable code?

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +                // edge case of double/float: -0.0 and 0.0 (we treat as non-equal arguments)
Would be nice to have a reference back to https://github.com/xunit/xunit/issues/1489 here.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +                var argumentSyntax = index < argumentSyntaxes.Count ? argumentSyntaxes[index] : null;
`index` is never modified, it's always 0. Probably not the intention.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +                var argumentSyntax = index < argumentSyntaxes.Count ? argumentSyntaxes[index] : null;
I wonder if there's some test coverage missing here for this case.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        internal override void AnalyzeCompilation(CompilationStartAnalysisContext compilationStartContext,
Unnecessary formatting and whitespace changes in this file.

2018-02-26 19:08 UTC, marcind commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        public class InlineDataUniquenessComparer : IEqualityComparer<AttributeData>
Why the change to `public`?

2018-03-01 22:36 UTC, wachulski commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +                var argumentSyntax = index < argumentSyntaxes.Count ? argumentSyntaxes[index] : null;
I admit, there was a bug and missing coverage indeed. Fixed in ArgumentValue.cs L 96 and unit tests added: DoesNotFind_WhenZeroAndNegativeZeroInlineDataOfDoubleOrFloatAsSecondTestMethodArguments

2018-03-01 22:37 UTC, wachulski commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        private static AttributeSyntax GetAttributeSyntax(SymbolAnalysisContext context, AttributeData attribute)
I reverted the cleanup, sorry for the inconvenience.

2018-03-01 22:37 UTC, wachulski commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        internal override void AnalyzeCompilation(CompilationStartAnalysisContext compilationStartContext,
I reverted the cleanup, sorry for the inconvenience.

2018-03-01 22:38 UTC, wachulski commented on src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs
> +        public class InlineDataUniquenessComparer : IEqualityComparer<AttributeData>
I forgot to make it back private after I had refactored. Done now.

2018-03-01 22:39 UTC, wachulski commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +                // edge case of double/float: -0.0 and 0.0 (we treat as non-equal arguments)
Sure thing. In place now.

2018-03-01 22:42 UTC, wachulski commented
@marcind 
> It looks like it achieves the goal of handling simple usages of negative/positive floating 0. As you state, it does not handle more complex (albeit unlikely to be used cases). I'd like to see a unit test for the unhandled case as a form of documentation that this is intentional

It was in there from the beginning: src/xunit.analyzers/InlineDataShouldBeUniqueWithinTheory.cs L 285

2018-03-01 23:05 UTC, wachulski commented
@marcind 
> As to the rewrite, seems like the goals was to a) simplify the code/reduce duplication and b) optimize performance by reducing boxing and allocations.

Well, a) is true but b) was not my intention at all. But I understand you may have thought like that, especially ArgumentValue.cs L 16 states: 

`This data structure should avoid allocations, hence structs (ImmutableArray with a builder) and no LINQ`

Why is it like that? All I wanted was to make the algorithm simpler as it operated on
1. TypedConstants
2. IParamterSymbols
3. (mixed) arrays of the above
That's why I introduced a common model that abstracts away how a test method argument is provided. Please note that I also had to bring argument syntaxes to the algorithm as TypedContants lack syntax info (for -0.0 or 0.0, they just provide the value which is 0.0), so do IParameterSymbols. The first version with pattern matching wasn't as smart as I initially had thought. Now it's simpler, just that. As for a new model I had to make a decision whether it should be a class or struct. I went for structs to avoid allocations.

So, the upshot: I strived for code simplicity (but I admit my remark may have misled you)

2018-03-01 23:06 UTC, wachulski commented
> I'm a little worried here because it looks like there's at least 1 place that introduces a bug (the unchanging index variable)

Bug fixed. Good catch thx.

2018-03-01 23:16 UTC, wachulski commented
> My suggestion would be to try what the -0.0 handling would look like in the existing algorithm, add the tests

I tried, but it was obvious that the code would get cluttered too much. I refactored first.

This is interesting, since after simplification it occured the previous version contained bugs. Lines:

`xArgPrimitive.Value != yMethodParamDefault.ExplicitDefaultValue` and
`xMethodParamDefault.ExplicitDefaultValue != yArgPrimitive.Value` were simply incorrect, e.g. for

`Finds_WhenDoubleNegativeOrPositiveZerosOfDoubleOrFloatFromParameterDefault` tests failed in cases:
`[InlineData("-0.0", "double")]` and `[InlineData("-0.0f", "float")]` since `(object) 0.0 != (object) 0.0`

Now it got changed to `Equals(Value, other.Value)` (ArgumentValue L 129) and should be ok.

2018-03-01 23:21 UTC, wachulski commented on src/xunit.analyzers/Utilities/ArgumentValue.cs
> +            return true;
Well, this is essential step in this recursive algorithm 🙂 All the preceding steps (except the first one) try to find a single difference which immidiately fails equality. The last one says: *no difference found, so - equal*

2018-05-28 10:24 UTC, wachulski commented
@marcind Ping. Any plans about this one?

2021-08-11 12:14 UTC, wachulski commented
Closing after a long time of no response/continuation.

2021-08-11 12:14 UTC, closed without merging